version: '3.8'

services:
  interactive-diagram-tool:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  # Development service (optional)
  dev:
    build:
      context: .
      target: builder
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev 